[build]
  functions = "functions"
  base = "/app/"
  publish = "dist/spa"
  command = "quasar build"

[dev]
  functions = "functions"
  port = 8888
  base = "/"
  command = "quasar dev"
  targetPort = 9696
  publish = "dist"

[[redirects]]
  from = '/*'
  to = '/index.html'
  status = 200

[[redirects]]
  from = '/api/*'
  to = '/.netlify/functions/:splat'
  status = 200